<?xml version="1.0" encoding="UTF-8"?><?oxygen RNGSchema="http://www.oasis-open.org/docbook/xml/5.0/rng/docbookxi.rng" type="xml"?>
<ns6563:section xmlns:ns6563="http://docbook.org/ns/docbook" xml:id="resources.information.technologies.java.j2se.exceptionHandling.whatHappensWithTheExceptions">
  <ns6564:title xmlns:ns6564="http://docbook.org/ns/docbook">What happens with the Exception?</ns6564:title>
  <ns6565:para xmlns:ns6565="http://docbook.org/ns/docbook">
    The exception is passed up the calling hierachy from client to client until either
    some or other high-level client catches the exception or until the highest level client,
      <ns6566:literal xmlns:ns6566="http://docbook.org/ns/docbook">main()</ns6566:literal> has been reached. If the exception is not
    caught in <ns6567:literal xmlns:ns6567="http://docbook.org/ns/docbook">main()</ns6567:literal> the application aborts with the
    message that some or other exception was thrown.
  </ns6565:para>
</ns6563:section>